% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Mar-2026 10:30:39
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------
saveVarsMat = load('TV1.mat');

E = 4.9242424242424239;

E1 = 5.125;

E2 = 4.9242424242424239;

N = [1 34 101 269 423 469 405 225 83 34 2];

N1 = [0 3 9 25 54 55 61 37 8 4 0];

N2 = [1 34 101 269 423 469 405 225 83 34 2];

a1 = [1 2 3];

a2 = [1 2 3];

ans = 2046;

ax = saveVarsMat.ax; % <1x2 matlab.graphics.axis.Axes> unsupported class

axes = saveVarsMat.axes; % <1x2 matlab.graphics.axis.Axes> unsupported class

delta = 0.1;

k = [0 1 2 3 4 5 6 7 8 9 10];

k2 = [0 1 2 3 4 5 6 7 8 9 10];

line1 = saveVarsMat.line1; % <1x1 matlab.graphics.chart.primitive.Bar> unsupported class

line2 = saveVarsMat.line2; % <1x1 matlab.graphics.chart.primitive.Bar> unsupported class

n = [1 34 101 269 423 469 405 225 83 34 2];

sigma = 1.6560646529585956;

sigma1 = 1.5612494995995996;

sigma2 = 1.6560646529585956;

x = [0 1 2 3 4 5 6 7 8 9 10];

y = [1 34 101 269 423 469 405 225 83 34 2];

clear saveVarsMat;
